version: '3.8'

services:
  feature1:
    build:
      context: ./apps/feature1
      dockerfile: Dockerfile
    container_name: micro-nuxt-feature1
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - micro-nuxt-network

  feature2:
    build:
      context: ./apps/feature2
      dockerfile: Dockerfile
    container_name: micro-nuxt-feature2
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    networks:
      - micro-nuxt-network

  nginx:
    image: nginx:alpine
    container_name: micro-nuxt-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - feature1
      - feature2
    networks:
      - micro-nuxt-network

networks:
  micro-nuxt-network:
    driver: bridge 